# frontend/Dockerfile.dev

FROM node:20

WORKDIR /app

# Copy only package.json first for faster rebuilds
COPY package*.json ./

# Install deps
RUN npm ci

# Copy the rest of your source
COPY . .

# Expose Angular’s default dev port
EXPOSE 4200

# Run the dev server with live-reload
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--poll=2000"]
