services:
  frontend:
    build: ./frontend
    ports: ['4200:80']
  backend:
    build: ./backend
    ports: ['3000:3000']
    environment:
      DB_HOST: db
  db:
    image: postgres:15
    ports: ['5432:5432']
    environment:
      POSTGRES_DB: menu_maker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
